Scenario_name: example

Ego:
  End_pos: [2,-2,40] # [road index, lane id, s]
  Start_pos: [0,2,40]
  Start_speed: 50

Map:
  - 121
  - 17
  - 144
  - 16

Agents:
  # Agent 1
  - Start_pos: [0,1,15]
    Start_speed: 10
    Start_trigger: # (reach init pos)
      lane: 2
      road: 0
      s: 20
      type: absolute
    Acts:
      - Type: turn # Agent1's Event1 
        Events:
        - Type: position
          Dynamic_delay: 0
          Dynamic_duration: 3
          Dynamic_shape: linear
          End: [3,-1,20]
          Use_route: [685.61,-134.05]
        - Type: speed # Action2 (speed)
          Dynamic_delay: 0
          Dynamic_duration: 2
          Dynamic_shape: linear
          End: 40
          Use_route: null