Scenario_name: config_example_zigzag

Ego:
  Start_pos: [0,-2,0]
  Start_speed: 50
  End_pos: [1,2,0] # [road index, lane id, s]

Map:
  - 139
  - 166

Agents:
  # Agent 1
  - Start_pos: [0,-2,15]
    Start_speed: 50
    Start_trigger: # (reach init pos)
      lane: 0
      road: -1
      s: 10
      type: relative
    Acts:
      - Type: zigzag 
        Events:
        - Type: offset 
          Dynamic_delay: 0 # (delay)
          Dynamic_duration: 1 # (period)
          Dynamic_shape: 10 # (offset)
          End: 2 # (times)
          Use_route: null
        - Type: speed
          Dynamic_delay: 0
          Dynamic_duration: 3
          Dynamic_shape: linear
          End: 30
          Use_route: null
      - Type: cut 
        Events:
        - Type: cut 
          Dynamic_delay: 0 
          Dynamic_duration: 2
          Dynamic_shape: sinusoidal
          End: 1
          Use_route: null
  - Start_pos: [0,-1,15]
    Start_speed: 10
    Start_trigger: # (reach init pos)
      lane: 1
      road: -1
      s: 10
      type: relative
    Acts:
      - Type: zigzag 
        Events:
        - Type: offset 
          Dynamic_delay: 0 # (delay)
          Dynamic_duration: 2 # (period)
          Dynamic_shape: -5 # (offset)
          End: 3 # (times)
          Use_route: null
        - Type: speed
          Dynamic_delay: 0
          Dynamic_duration: 3
          Dynamic_shape: linear
          End: 40
          Use_route: null
      